collections:
  hotelposts:
    output: true
    permalink: /hotels/:slug
  hotelarchives:
    output: true
    permalink: /hotel/:title
  destposts:
    output: true
    permalink: /destinations/:slug
  destarchives:
    output: true
    permalink: /dest/:title
  tourposts:
    output: true
    permalink: /tours/:slug
  tourarchives:
    output: true
    permalink: /trs/:title
  excposts:
    output: true
    permalink: /excursions/:slug
  excarchives:
    output: true
    permalink: /exc/:title
    

defaults:
  -
    scope:
      path: ""
      type: "hotelposts"
    values:
      layout: "hotel-layout"

# Ensure Jekyll processes categories correctly
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layouts:
    category: archive
  permalinks:
    category: /category/:name/


